export const FakedData =
{
     data : [
        {
            id: 1,
            firstName: 'John',
            lastName: 'Doe',
            age: 30,
            email: 'john@example.com',
            address: '123 Main St',
            city: 'New York',
            state: 'NY',
            country: 'USA',
            phone: '+1 (555) 123-4567',
            occupation: 'Engineer',
        },
        {
            id: 2,
            firstName: 'Jane',
            lastName: 'Smith',
            age: 28,
            email: 'jane@example.com',
            address: '456 Elm St',
            city: 'Los Angeles',
            state: 'CA',
            country: 'USA',
            phone: '+1 (555) 987-6543',
            occupation: 'Designer',
        },
        {
            id: 3,
            firstName: 'Bob',
            lastName: 'Johnson',
            age: 35,
            email: 'bob@example.com',
            address: '789 Oak St',
            city: 'Chicago',
            state: 'IL',
            country: 'USA',
            phone: '+1 (555) 321-7890',
            occupation: 'Manager',
        },
        {
            id: 4,
            firstName: 'Alice',
            lastName: 'Williams',
            age: 27,
            email: 'alice@example.com',
            address: '101 Pine St',
            city: 'San Francisco',
            state: 'CA',
            country: 'USA',
            phone: '+1 (555) 456-7890',
            occupation: 'Doctor',
        },
        {
            id: 5,
            firstName: 'Michael',
            lastName: 'Brown',
            age: 32,
            email: 'michael@example.com',
            address: '222 Cedar St',
            city: 'Houston',
            state: 'TX',
            country: 'USA',
            phone: '+1 (555) 987-1234',
            occupation: 'Teacher',
        },
        {
            id: 6,
            firstName: 'Emily',
            lastName: 'Davis',
            age: 29,
            email: 'emily@example.com',
            address: '333 Maple St',
            city: 'Miami',
            state: 'FL',
            country: 'USA',
            phone: '+1 (555) 234-5678',
            occupation: 'Artist',
        },
        {
            id: 7,
            firstName: 'David',
            lastName: 'Wilson',
            age: 40,
            email: 'david@example.com',
            address: '444 Birch St',
            city: 'Dallas',
            state: 'TX',
            country: 'USA',
            phone: '+1 (555) 789-0123',
            occupation: 'Engineer',
        },
        {
            id: 8,
            firstName: 'Olivia',
            lastName: 'Moore',
            age: 26,
            email: 'olivia@example.com',
            address: '555 Oak St',
            city: 'Seattle',
            state: 'WA',
            country: 'USA',
            phone: '+1 (555) 345-6789',
            occupation: 'Writer',
        },
        {
            id: 9,
            firstName: 'William',
            lastName: 'Lee',
            age: 33,
            email: 'william@example.com',
            address: '666 Pine St',
            city: 'Boston',
            state: 'MA',
            country: 'USA',
            phone: '+1 (555) 123-9876',
            occupation: 'Scientist',
        },
        {
            id: 10,
            firstName: 'Sophia',
            lastName: 'Taylor',
            age: 31,
            email: 'sophia@example.com',
            address: '777 Elm St',
            city: 'Philadelphia',
            state: 'PA',
            country: 'USA',
            phone: '+1 (555) 987-6543',
            occupation: 'Lawyer',
        },
        {
            id: 11,
            firstName: 'John',
            lastName: 'Doe',
            age: 30,
            email: 'john@example.com',
            address: '123 Main St',
            city: 'New York',
            state: 'NY',
            country: 'USA',
            phone: '+1 (555) 123-4567',
            occupation: 'Engineer',
        },
        {
            id: 12,
            firstName: 'Jane',
            lastName: 'Smith',
            age: 28,
            email: 'jane@example.com',
            address: '456 Elm St',
            city: 'Los Angeles',
            state: 'CA',
            country: 'USA',
            phone: '+1 (555) 987-6543',
            occupation: 'Designer',
        },
        {
            id: 13,
            firstName: 'Bob',
            lastName: 'Johnson',
            age: 35,
            email: 'bob@example.com',
            address: '789 Oak St',
            city: 'Chicago',
            state: 'IL',
            country: 'USA',
            phone: '+1 (555) 321-7890',
            occupation: 'Manager',
        },
        {
            id: 14,
            firstName: 'Alice',
            lastName: 'Williams',
            age: 27,
            email: 'alice@example.com',
            address: '101 Pine St',
            city: 'San Francisco',
            state: 'CA',
            country: 'USA',
            phone: '+1 (555) 456-7890',
            occupation: 'Doctor',
        },
        {
            id: 15,
            firstName: 'Michael',
            lastName: 'Brown',
            age: 32,
            email: 'michael@example.com',
            address: '222 Cedar St',
            city: 'Houston',
            state: 'TX',
            country: 'USA',
            phone: '+1 (555) 987-1234',
            occupation: 'Teacher',
        },
        {
            id: 16,
            firstName: 'Emily',
            lastName: 'Davis',
            age: 29,
            email: 'emily@example.com',
            address: '333 Maple St',
            city: 'Miami',
            state: 'FL',
            country: 'USA',
            phone: '+1 (555) 234-5678',
            occupation: 'Artist',
        },
        {
            id: 17,
            firstName: 'David',
            lastName: 'Wilson',
            age: 40,
            email: 'david@example.com',
            address: '444 Birch St',
            city: 'Dallas',
            state: 'TX',
            country: 'USA',
            phone: '+1 (555) 789-0123',
            occupation: 'Engineer',
        },
        {
            id: 18,
            firstName: 'Olivia',
            lastName: 'Moore',
            age: 26,
            email: 'olivia@example.com',
            address: '555 Oak St',
            city: 'Seattle',
            state: 'WA',
            country: 'USA',
            phone: '+1 (555) 345-6789',
            occupation: 'Writer',
        },
        {
            id: 19,
            firstName: 'William',
            lastName: 'Lee',
            age: 33,
            email: 'william@example.com',
            address: '666 Pine St',
            city: 'Boston',
            state: 'MA',
            country: 'USA',
            phone: '+1 (555) 123-9876',
            occupation: 'Scientist',
        },
        {
            id: 20,
            firstName: 'Sophia',
            lastName: 'Taylor',
            age: 31,
            email: 'sophia@example.com',
            address: '777 Elm St',
            city: 'Philadelphia',
            state: 'PA',
            country: 'USA',
            phone: '+1 (555) 987-6543',
            occupation: 'Lawyer',
        },
        {
            id: 21,
            firstName: 'John',
            lastName: 'Doe',
            age: 30,
            email: 'john@example.com',
            address: '123 Main St',
            city: 'New York',
            state: 'NY',
            country: 'USA',
            phone: '+1 (555) 123-4567',
            occupation: 'Engineer',
        },
        {
            id: 22,
            firstName: 'Jane',
            lastName: 'Smith',
            age: 28,
            email: 'jane@example.com',
            address: '456 Elm St',
            city: 'Los Angeles',
            state: 'CA',
            country: 'USA',
            phone: '+1 (555) 987-6543',
            occupation: 'Designer',
        },
        {
            id: 23,
            firstName: 'Bob',
            lastName: 'Johnson',
            age: 35,
            email: 'bob@example.com',
            address: '789 Oak St',
            city: 'Chicago',
            state: 'IL',
            country: 'USA',
            phone: '+1 (555) 321-7890',
            occupation: 'Manager',
        },
        {
            id: 24,
            firstName: 'Alice',
            lastName: 'Williams',
            age: 27,
            email: 'alice@example.com',
            address: '101 Pine St',
            city: 'San Francisco',
            state: 'CA',
            country: 'USA',
            phone: '+1 (555) 456-7890',
            occupation: 'Doctor',
        },
        {
            id: 25,
            firstName: 'Michael',
            lastName: 'Brown',
            age: 32,
            email: 'michael@example.com',
            address: '222 Cedar St',
            city: 'Houston',
            state: 'TX',
            country: 'USA',
            phone: '+1 (555) 987-1234',
            occupation: 'Teacher',
        },
        {
            id: 26,
            firstName: 'Emily',
            lastName: 'Davis',
            age: 29,
            email: 'emily@example.com',
            address: '333 Maple St',
            city: 'Miami',
            state: 'FL',
            country: 'USA',
            phone: '+1 (555) 234-5678',
            occupation: 'Artist',
        },
        {
            id: 27,
            firstName: 'David',
            lastName: 'Wilson',
            age: 40,
            email: 'david@example.com',
            address: '444 Birch St',
            city: 'Dallas',
            state: 'TX',
            country: 'USA',
            phone: '+1 (555) 789-0123',
            occupation: 'Engineer',
        },
        {
            id: 28,
            firstName: 'Olivia',
            lastName: 'Moore',
            age: 26,
            email: 'olivia@example.com',
            address: '555 Oak St',
            city: 'Seattle',
            state: 'WA',
            country: 'USA',
            phone: '+1 (555) 345-6789',
            occupation: 'Writer',
        },
        {
            id: 29,
            firstName: 'William',
            lastName: 'Lee',
            age: 33,
            email: 'william@example.com',
            address: '666 Pine St',
            city: 'Boston',
            state: 'MA',
            country: 'USA',
            phone: '+1 (555) 123-9876',
            occupation: 'Scientist',
        },
        {
            id: 30,
            firstName: 'Sophia',
            lastName: 'Taylor',
            age: 31,
            email: 'sophia@example.com',
            address: '777 Elm St',
            city: 'Philadelphia',
            state: 'PA',
            country: 'USA',
            phone: '+1 (555) 987-6543',
            occupation: 'Lawyer',
        },
        {
            id: 31,
            firstName: 'John',
            lastName: 'Doe',
            age: 30,
            email: 'john@example.com',
            address: '123 Main St',
            city: 'New York',
            state: 'NY',
            country: 'USA',
            phone: '+1 (555) 123-4567',
            occupation: 'Engineer',
        },
        {
            id: 32,
            firstName: 'Jane',
            lastName: 'Smith',
            age: 28,
            email: 'jane@example.com',
            address: '456 Elm St',
            city: 'Los Angeles',
            state: 'CA',
            country: 'USA',
            phone: '+1 (555) 987-6543',
            occupation: 'Designer',
        },
        {
            id: 33,
            firstName: 'Bob',
            lastName: 'Johnson',
            age: 35,
            email: 'bob@example.com',
            address: '789 Oak St',
            city: 'Chicago',
            state: 'IL',
            country: 'USA',
            phone: '+1 (555) 321-7890',
            occupation: 'Manager',
        },
        {
            id: 34,
            firstName: 'Alice',
            lastName: 'Williams',
            age: 27,
            email: 'alice@example.com',
            address: '101 Pine St',
            city: 'San Francisco',
            state: 'CA',
            country: 'USA',
            phone: '+1 (555) 456-7890',
            occupation: 'Doctor',
        },
        {
            id: 35,
            firstName: 'Michael',
            lastName: 'Brown',
            age: 32,
            email: 'michael@example.com',
            address: '222 Cedar St',
            city: 'Houston',
            state: 'TX',
            country: 'USA',
            phone: '+1 (555) 987-1234',
            occupation: 'Teacher',
        },
        {
            id: 36,
            firstName: 'Emily',
            lastName: 'Davis',
            age: 29,
            email: 'emily@example.com',
            address: '333 Maple St',
            city: 'Miami',
            state: 'FL',
            country: 'USA',
            phone: '+1 (555) 234-5678',
            occupation: 'Artist',
        },
        {
            id: 37,
            firstName: 'David',
            lastName: 'Wilson',
            age: 40,
            email: 'david@example.com',
            address: '444 Birch St',
            city: 'Dallas',
            state: 'TX',
            country: 'USA',
            phone: '+1 (555) 789-0123',
            occupation: 'Engineer',
        },
        {
            id: 38,
            firstName: 'Olivia',
            lastName: 'Moore',
            age: 26,
            email: 'olivia@example.com',
            address: '555 Oak St',
            city: 'Seattle',
            state: 'WA',
            country: 'USA',
            phone: '+1 (555) 345-6789',
            occupation: 'Writer',
        },
        {
            id: 39,
            firstName: 'William',
            lastName: 'Lee',
            age: 33,
            email: 'william@example.com',
            address: '666 Pine St',
            city: 'Boston',
            state: 'MA',
            country: 'USA',
            phone: '+1 (555) 123-9876',
            occupation: 'Scientist',
        },
        {
            id: 40,
            firstName: 'Sophia',
            lastName: 'Taylor',
            age: 31,
            email: 'sophia@example.com',
            address: '777 Elm St',
            city: 'Philadelphia',
            state: 'PA',
            country: 'USA',
            phone: '+1 (555) 987-6543',
            occupation: 'Lawyer',
        },
    ],
    column:[
        { header: 'ID', field: 'id' },
        { header: 'FirstName', field: 'firstName' },
        { header: 'lastName', field: 'lastName' },
        { header: 'Age', field: 'age' },
        { header: 'Email', field: 'email' },
        { header: 'Address', field: 'address' },
        { header: 'City', field: 'city' },
        { header: 'State', field: 'state' },
        { header: 'Country', field: 'country' },
        { header: 'Phone', field: 'phone' },
        { header: 'Occupation', field: 'occupation' },
    ],
};

export default FakedData;
